# Generated by Django 5.2.4 on 2025-07-22 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customers', '0002_alter_customersmodel_options'),
        ('app_employies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumberGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_runing_number', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ສ້າງເລກໃບເກັບເງິນອັດຕະໂນມັດ',
                'verbose_name_plural': 'ສ້າງເລກໃບເກັບເງິນອັດຕະໂນມັດ',
            },
        ),
        migrations.CreateModel(
            name='InvoiceInformationModel',
            fields=[
                ('invoice_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('expired_date', models.DateField()),
                ('status', models.CharField(choices=[('sended', 'ສົ່ງໃບເກັບເງິນແລ້ວ'), ('paid', 'ຈ່າຍແລ້ວ'), ('pending', 'ລໍຖ້າການຈ່າຍເງິນ'), ('cancelled', 'ຍົກເລີກ')], default='sended', max_length=20)),
                ('total_all_products', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('create_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_invoice_by', to='app_employies.employiesmodel')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_customer_information', to='app_customers.customersmodel')),
            ],
            options={
                'verbose_name': 'ຂໍ້ມູນໃບເກັບເງິນ',
                'verbose_name_plural': 'ຂໍ້ມູນໃບເກັບເງິນ',
            },
        ),
        migrations.CreateModel(
            name='AdditionalExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_all_products_ref', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('it_service_percent', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('vat_percent', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('it_service_output', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('vat_output', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('exchange_rate_output', models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=20, null=True)),
                ('grandTotal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_expenses', to='app_invoices.invoiceinformationmodel')),
            ],
            options={
                'verbose_name': 'ຄ່າໃຊ້ຈ່າຍເພີ່ມເຕີ່ມ',
                'verbose_name_plural': 'ຄ່າໃຊ້ຈ່າຍເພີ່ມເຕີ່ມ',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('period', models.IntegerField(default=12)),
                ('total_one_product', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_invoices.invoiceinformationmodel')),
            ],
            options={
                'verbose_name': 'ລາຍການສິນຄ້າ',
                'verbose_name_plural': 'ລາຍການສິນຄ່າ',
            },
        ),
    ]
