# Generated by Django 5.2.4 on 2025-07-25 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0002_alter_customersmodel_options'),
        ('app_invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceinformationmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_customer_information', to='app_customers.customersmodel'),
        ),
    ]
