# Generated by Django 5.2.3 on 2025-07-01 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersIdGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_running_number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=30)),
                ('contact_person_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('company_address', models.CharField(max_length=255)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'CustomersModel',
                'verbose_name_plural': 'CustomersModel',
                'ordering': ('-create_at',),
            },
        ),
    ]
