# Generated by Django 5.2.4 on 2025-07-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customersmodel',
            options={'ordering': ('-create_at',), 'verbose_name': 'ຂໍ້ມູນກ່ຽວກັບລູກຄ້າ', 'verbose_name_plural': 'ຂໍ້ມູນກ່ຽວກັບລູກຄ້າ'},
        ),
    ]
