# Generated by Django 5.2.3 on 2025-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsmodel',
            name='status',
            field=models.CharField(choices=[('ສັ່ງໃບເສະເຫນີລາຄາ', 'ສັ່ງ\u0e83ັບເສະເຫນີລາຄາ'), ('ປິດການຂາย', 'ປິດກາนຂາย'), ('ປະຕິເສິດກາนຂາย', 'ປະຕິເສິດກາนຂາย')], default='ສັ່ງໃບເສະເຫນີລາຄາ', max_length=30),
        ),
    ]
