# Generated by Django 5.2.3 on 2025-07-01 08:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotations', '0002_alter_quotationsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalexpensesmodel',
            name='grand_total_sum_all',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='quotationsmodel',
            name='total_one_product',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
    ]
