# Generated by Django 5.2.3 on 2025-07-01 08:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0001_initial'),
        ('app_quotations', '0003_alter_additionalexpensesmodel_grand_total_sum_all_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalexpensesmodel',
            options={'verbose_name': 'Additional Expenses', 'verbose_name_plural': 'Additional Expenses'},
        ),
        migrations.AlterModelOptions(
            name='quotationsmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='additionalexpensesmodel',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='additionalexpensesmodel',
            name='rate_usd',
        ),
        migrations.RemoveField(
            model_name='quotationsmodel',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='quotationsmodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotationsmodel',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='quotationsmodel',
            name='quotation_number',
        ),
        migrations.RemoveField(
            model_name='quotationsmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='additionalexpensesmodel',
            name='exchange_result',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='additionalexpensesmodel',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='additionalexpensesmodel',
            name='grand_total_sum_all',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='additionalexpensesmodel',
            name='it_service',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='additionalexpensesmodel',
            name='it_service_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='additionalexpensesmodel',
            name='sum_all_products',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='additionalexpensesmodel',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='additionalexpensesmodel',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='quotationsmodel',
            name='total_one_product',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='QuotationGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('expired_at', models.DateField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app_customers.customersmodel')),
            ],
            options={
                'ordering': ['quotation_number'],
            },
        ),
        migrations.AddField(
            model_name='additionalexpensesmodel',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_expenses', to='app_quotations.quotationgroupmodel'),
        ),
        migrations.AddField(
            model_name='quotationsmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_quotations.quotationgroupmodel'),
        ),
    ]
