# Generated by Django 5.2.3 on 2025-07-01 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customers', '0001_initial'),
        ('app_quotations', '0004_alter_additionalexpensesmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationsmodel',
            name='group',
        ),
        migrations.RemoveField(
            model_name='additionalexpensesmodel',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='additionalexpensesmodel',
            options={'verbose_name': 'Additional Expense', 'verbose_name_plural': 'Additional Expenses'},
        ),
        migrations.AlterModelOptions(
            name='quotationsmodel',
            options={'ordering': ['quotation_number'], 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
        migrations.AddField(
            model_name='additionalexpensesmodel',
            name='quotation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_expenses', to='app_quotations.quotationsmodel'),
        ),
        migrations.AddField(
            model_name='quotationsmodel',
            name='create_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationsmodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='app_customers.customersmodel'),
        ),
        migrations.AddField(
            model_name='quotationsmodel',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationsmodel',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='quotationsmodel',
            name='status',
            field=models.CharField(choices=[('ສັ່ງໃບເສະເຫນີລາຄາ', 'ສັ່ງໃບເສະເຫນີລາຄາ'), ('ປິດການຂາຍ', 'ປິດການຂາຍ'), ('ປະຕິເສິດການຂາຍ', 'ປະຕິເສິດການຂາຍ')], default='ສັ່ງໃບເສະເຫນີລາຄາ', max_length=30),
        ),
        migrations.AlterField(
            model_name='quotationsmodel',
            name='total_one_product',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='QuotationGroupModel',
        ),
    ]
