# Generated by Django 5.2.4 on 2025-07-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotations', '0006_remove_quotationsmodel_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalexpensesmodel',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationitemsmodel',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='QuotationNumberGenerator',
        ),
        migrations.RemoveField(
            model_name='quotationsmodel',
            name='customer',
        ),
        migrations.DeleteModel(
            name='AdditionalExpensesModel',
        ),
        migrations.DeleteModel(
            name='QuotationItemsModel',
        ),
        migrations.DeleteModel(
            name='QuotationsModel',
        ),
    ]
