# Generated by Django 5.2.4 on 2025-07-08 05:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customers', '0001_initial'),
        ('app_quotations', '0007_remove_additionalexpensesmodel_quotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationIdGeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id_runing_number', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'ສ້າງເລກໃບສະເຫນີລາຄາອັດຕະໂນມັດ',
                'verbose_name_plural': 'ສ້າງເລກໃບສະເຫນີລາຄາອັດຕະໂນມັດ',
            },
        ),
        migrations.CreateModel(
            name='QuotationInformationModel',
            fields=[
                ('quotation_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('expired_date', models.DateField()),
                ('status', models.CharField(choices=[('sended', 'ສົ່ງໃບສະເຫນີລາຄາ'), ('closed', 'ປິດການຂາຍ'), ('cancelled', 'ຍົກເລີກການຂາຍ')], default='sended', max_length=20)),
                ('total_all_products', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_information', to='app_customers.customersmodel')),
            ],
            options={
                'verbose_name': 'ຂໍ້ມູນໃບສະເຫນີລາຄາ',
                'verbose_name_plural': 'ຂໍ້ມູນໃບສະເຫນີລາຄາ',
                'ordering': ('-expired_date',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_all_products_ref', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('it_service_percent', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('vat_percent', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.00'), max_digits=10, null=True)),
                ('it_sevice_output', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('vat_output', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('exchange_rate_output', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('grandTotal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True)),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_expenses', to='app_quotations.quotationinformationmodel')),
            ],
            options={
                'verbose_name': 'ຄ່າໃຊ້ຈ່າຍເພີ່ມເຕີ່ມ',
                'verbose_name_plural': 'ຄ່າໃຊ້ຈ່າຍເພີ່ມເຕີ່ມ',
            },
        ),
        migrations.CreateModel(
            name='QuotationItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField()),
                ('period', models.IntegerField(default=12)),
                ('total_one_product', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_quotations.quotationinformationmodel')),
            ],
            options={
                'verbose_name': 'ລາຍການສິນຄ້າ',
                'verbose_name_plural': 'ລາຍການສິນຄ້າ',
            },
        ),
    ]
