# Generated by Django 5.2.4 on 2025-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotations', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalexpenses',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionalexpenses',
            name='exchange_rate_output',
            field=models.DecimalField(blank=True, decimal_places=0, editable=False, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionalexpenses',
            name='it_service_percent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='additionalexpenses',
            name='vat_percent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='quotationinformationmodel',
            name='create_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quotationinformationmodel',
            name='total_all_products',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, null=True),
        ),
    ]
