# Generated by Django 5.2.4 on 2025-07-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_employies', '0001_initial'),
        ('app_quotations', '0009_alter_additionalexpenses_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationinformationmodel',
            name='create_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation', to='app_employies.employiesmodel'),
        ),
    ]
