# Generated by Django 5.2.4 on 2025-07-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('sale', 'Sale User'), ('finance', 'Finance User'), ('admin', 'Admin'), ('super', 'Super User')], default='sale', max_length=10),
        ),
    ]
