# Generated by Django 5.2.4 on 2025-07-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
