# Generated by Django 5.2.4 on 2025-07-09 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployiesModel',
            fields=[
                ('employies_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employies_name', models.CharField(max_length=30)),
                ('employies_lastname', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('signature', models.ImageField(upload_to='employies_signatures')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ຂໍ້ມູນພະນັກງານ',
                'verbose_name_plural': 'ຂໍ້ມູນພະນັກງານ',
                'ordering': ('employies_id',),
            },
        ),
    ]
